apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
