---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-managed-traefik
  namespace: traefik-system
spec:
  encryptedData:
    CROWDSEC_LAPI_KEY: AgAqRYgAv2NHulTUcL4h4xUgsOcDInXXMeNP8FFmtwBWQi4PgcxtKlcSCcIFHe8n7m57hyBe0A2aXEhrmtewJtom1qcaRlHHbV+FTd5BBhSApzdQObVeiFimO+yQ4WnVFVAq7VbA/mDmmZQtEeVaLCgEgHpxP5fRzRn3tN4rGSpFE5nCqOW9PH4kX9GYYiuT++xt8dYT32ikFZ0d8sIzhhCyQ9AF3nkXmTwL/j0UFzE0eyIIPy+zAqjdrkyLQcVDmc0YIDHa6Ma+upf0T3HeOETx0OymPfjoqtiY2y65PLwQuXN++MajAay3CkDt4HZkoj9kzi2xTDkyOLNo5ozoYDtdNgLfaSV7UoGmbSN0zHsmWr4N8zO5itD7hWXTmxz6h2VWxTNZOHIaeIh/9Aq4LT/FLmXmocoQpvBNZly5ZRctr0m7L4z9CTAXeH2bn6WCCDM8S5k52gjNQjGWLEKlqim1Zb+EQKHGT2XfuXxLtGPPzQ4+l+VJMZWGrNBRKlOakFvvNKOK+323Uw9XH+EL3c950tVXb7Db0bMt9sICFYD5x/pQMBY10hvqqDhK+mcR4zXHLsM2XTUdyX4ING4S1TY1HnonVWX/LRrk4n5Wg7jFl2z7SqMfGH88F8izV/imqxhZmnHHmpOnH9ugxyLlkeqgrwSMTeFstd0tiOOuYpyqMENAXJrPPZQ82LWT2q7JNXQDX6m8qG2Wp41W7O4RocEM+tYmveTlZI1QJOII+vZSYh4+rRi87YbARHB1
  template:
    metadata:
      name: infisical-managed-traefik
      namespace: traefik-system
