apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-system
  labels:
    app.kubernetes.io/name: tailscale-operator
    app.kubernetes.io/component: vpn
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
