# apps namespace
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-sync-apps
  namespace: apps
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: homelab
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: apps
      secretsScope:
        projectSlug: homelab-ahe-r
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: infisical-managed-apps
    secretNamespace: apps
    creationPolicy: Owner
---
# immich namespace
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-sync-immich
  namespace: immich
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: homelab
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: immich
      secretsScope:
        projectSlug: homelab-ahe-r
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: infisical-managed-immich
    secretNamespace: immich
    creationPolicy: Owner
---
# monitoring namespace
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-sync-monitoring
  namespace: monitoring
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: homelab
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: monitoring
      secretsScope:
        projectSlug: homelab-ahe-r
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: infisical-managed-monitoring
    secretNamespace: monitoring
    creationPolicy: Owner
---
# traefik-system namespace
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-sync-traefik
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: homelab
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: traefik-system
      secretsScope:
        projectSlug: homelab-ahe-r
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: infisical-managed-traefik
    secretNamespace: traefik-system
    creationPolicy: Owner
---
# networking namespace
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-sync-networking
  namespace: networking
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: homelab
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: networking
      secretsScope:
        projectSlug: homelab-ahe-r
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: infisical-managed-networking
    secretNamespace: networking
    creationPolicy: Owner
