apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infisical
  namespace: infisical
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`secrets.ukkiee.dev`)
      kind: Rule
      middlewares:
        - name: tailscale-only
          namespace: traefik-system
        - name: security-headers
          namespace: traefik-system
      services:
        - name: infisical-infisical-standalone-infisical
          port: 8080
