apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
  namespace: test-web
  labels:
    app.kubernetes.io/name: test-web
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: argocd
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-web
        app.kubernetes.io/version: latest
    spec:
      priorityClassName: standard
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-pull-secret
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: test-web
          image: ghcr.io/ukkiee-dev/test-web:40936b66fb19c62dda536c8fa91c64ec443dcf08
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
