apiVersion: v1
kind: Service
metadata:
  name: test-web
  namespace: test-web
  labels:
    app.kubernetes.io/name: test-web
spec:
  selector:
    app.kubernetes.io/name: test-web
  ports:
    - port: 3000
      targetPort: 3000
