apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/component: database-operator
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
