apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    app.kubernetes.io/name: arc-runners
    app.kubernetes.io/component: cicd
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
