apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - appproject-infra.yaml
  - appproject-apps.yaml
  - appproject-monitoring.yaml
  - ingressroute.yaml
  - ingressroute-api.yaml
  - network-policy.yaml
