# ArgoCD Helm Values
# helm repo add argo https://argoproj.github.io/argo-helm
# helm install argocd argo/argo-cd -n argocd -f values.yaml

configs:
  cm:
    url: https://argo.ukkiee.dev
    accounts.ukkiee: apiKey, login
  rbac:
    policy.csv: |
      g, ukkiee, role:admin

server:
  extraArgs:
    - --insecure  # Traefik handles TLS

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

controller:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

repoServer:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi

redis:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false
