apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pokopia-wiki-backup
  namespace: pokopia-wiki
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  configuration:
    # s3://homelab-db-backups/<app>/<cluster>/{base,wals}
    destinationPath: s3://homelab-db-backups/pokopia-wiki
    endpointURL: https://142c501381145f1d42bd2b8107be8a0e.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: r2-pg-backup
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: r2-pg-backup
        key: SECRET_ACCESS_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: "14d"
