---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-pg-backup
  namespace: pokopia-wiki
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAW8nqCYh9bGFqwfPawXWWFiHBTmt8J4UejHNMkVcZjR++We7hiqsffMgCssqnFeevCkFq+MLv65QBz897/OofV16HiYWuJ/6oDHBlVpctR6NI6Zad+UJ1gSGQnEg/9JrbUHeTVWklTAxHaUKOBt8EuojRZF6o7mQyILecmBU86fcd969FL9+reCzieyS1e6wIY4uV7+i72GU0mjtK7iPI2NJnGHwnR5mcwP1S5BvfeFmb58NRiq+30lr+71G5nmbBHbL/2XwRGG10R2LRQBJM618P/aHA5hmuZty2Fs094D4vhWJY45lTui8Gtk9ru5kZAcsiRmlsEsC5OvcOM7+C8mMuQ2znuBaE+8W0/2o32F2yd/LyRND0cKdcHCrnJ34hX3GAPXSX6tuLpnXJgxqPW8LJoXQM5pPSZ5OD/P2L3HTJ383tpCmDrtEFqbi5mwYz+HgG4MB0Bp5jj4ezXEbYINVVFSGycvxQzXGRoI/CFAvthH7ctqVYh01KZRphqnm//2snpOR4BKeuLxpxak0eigha9D2n1N3mJp17MrElD+iFMj+egD7nJYwtfBxI7naXptl4x/rXKvPKshmkUo4LTpHmktRWsyGnRLuwfl25ZUitvU2N664jXOZ38KCY5xqrNXIXX+Qkq+TnWFqkW5TBw51ujt3jbOjynOWvE1Ffrq1BFYKub+TtDP1meYb0X/ma9GCqnk0M/9xhIPeSzR+c5QUnUZF5wICL8kAe9abYMdw==
    SECRET_ACCESS_KEY: AgBZVm3rRH9yqA/qj5LyMMFO8/QgOqrJMcPN83OscQX9NKP9WOM2XiUDBE48qYiuCh99e1rmdVCeeNk4jC0Sf9zOyCGVtWeu6351M9+G+pwoeTD2+fNwAHHeA2J9ZASEjf0taMgefCG1MqjWRWy94yo8DF5trVPa5qTTZaQOBhPN8Z8cpbTxcOPscSUtaSnJv3AAnU1qMGgf8gSxR8hze6H4au5ZNI+6NVDWDDJP31/rU3OILndnc7Ow8HcQprrmiqVrOzf/arpc9HvkzYMIMJsS/3vq/WtOLiVmlOXIXn3g5oh9+O9SUI6UZPSD6UK1ltj+Vf/7y+q7xcCdkM6Rnau3A2HC1tnqH3KY5RUQPVrq0lMXA5qSh1/dLzGM2nTH0PFbC5poMQ2CTwn/CWMKG+cSG/mts2745HqOYod+EGg6o2DynDRWEh5lPetUsOx0i9BGN/ZOlOaLov9wBXQGIOuNvCONEqRsSZ730W0ERDXa1ni0cz39DtKVQgiPXIIapUHw5UNwMssTzXHlh9QR4b3yNmpfYgslt0+Kq9Zkn3PIp8YQ6g/qJ0Jw6VvdR5a2XH+lxl35vDyLaVedZbdcERZQHNc30wCvT7rfQrvv+8xoFXzqAdkzTMXPUr2kuPOYE7isAZ/adL1ypKqbWBLq1rgA9pZgMf26Q1/jmF5GZ54M5XLznC2/TffK/7cc6BqsPQok7IPRUHn4Ud+39dbWkCmKloKaWc/O5ObTlJ8iqtXcHPKg3Pd1jPn2Kt2Ax7O7hn/UjFx/Hrw8ymc5vlJQUu85
  template:
    metadata:
      name: r2-pg-backup
      namespace: pokopia-wiki
    type: Opaque
