---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-pg-backup
  namespace: pokopia-wiki
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAM0ak117chVluLSnDnDszIBEVkLuoWf34SNZg33TAH/DwtXbZUme7aw53BehDH9rkwT8RG0DYlM4cxWrY++WCv/8nlu5UoDg86mT3eZhZFFbqlPkYLuvnnOkepg6AKaPw0ua0JbVh9obzg5fjT7ncCUILa2qoexZlk4bTPm6E8cDcMCkkCH1VOIZlg1BAXGFY5o9Np1KpUkLVNyT29eVqJGVjDrgnBakFFPGIrJSWx7H3razWnD1rTZ/WwAKGhTG0iV9o1MhSHP2mwd6oyq7uOyIyNCh7thWujdvZ1WzKZRsglkGVXQtQnxW9xdBKi1oMVQZdERBYksANmyLX2J/jVSG2Fpd8hZ/18UinWshujGHqdvVtLWtus5ArhU4CBylL+4yV/kCEimgzJ7S7H0a/CmZ7V5Lh2sAx112A0B3CE/uaFaWvtpzhPGsch6DzBK6OUzLrBO5BdU7RtKPGMqu+3FhzUkclIpgZ2a3DDoOOAt5Hne2iVR1mwY49Zob7o6PHWuY9oYzgEz9Ak8QhYYL5ExiQ0e+PphVPv/tj1vuhPz1GWHr/ky8pyb7rg1NNJLG4CKsl0V0+8J1nDLMUycp5fQwZcAe6na2XewWVF+rT64NeF4Ux0ngq7jcgtZUR2WGLZxpVHN9cesRPOejtgQG2NMiIox9npAeVEIjJJ6sA9mBveFfDcL/6v1WyXjnI64Hz0XYcxrD0yMFyjPVRYkMrBOcc3UvgJgNsDakF+OjUPrw==
    SECRET_ACCESS_KEY: AgCoe3vj47IEEVUeyowNwnU9VM8jZrr29S7PnufNrdaN6f8yxtrwjxuym+CE07P6/6Kut8+Pf8+WqJc6FRvXD7ChnxrgQnFIdAuqayCgF8D4AAdumLC1Qd35BLnq4ZmMngkoYkvEBCCJi9QCuHNXcBs6+wOB2DqV6XHuNjgxzkDQAYilaEByGceXLdP2f/fuTFnuUQxVQxLY9jpDJwvv3x+YhWspJIeCmzi+37yvds8ZUAUzNfspHj2GkUqWh9H/T1BBtxhTAQaWNImV0UmlvL3Qsdz5XY0xzciEesjD4hSeR5u+FWdTim6oXNB5Rs5mn2ntRsLaSQta6jUgAzGmnYsNo8ajk88fnDwp+XWlosf91Y04jm3nKjhzKBXrChuAif+PVYbINr/NOzd7PJupwVS0AGFgoSb0QBS9a+tDJOslny0DNisHTtL02dAMpZllaxeY2M0FkArNcJUOYuM73JIov59zQzZFMQxVLxDNQg/LIlDGA+hGr2/7xzQTADhRenU5lk499kCfI5JS74h26SqF5i3owHfJFASpv1OVReD7gEeOSL1uhau706rFGNgnlAkp83+pTM5zlF6QNjOldpjvWCaWVpWhSxHDTB1LgCW9xxg9ozkgUcxNJI9VJbV2xoZLN60r2hYBzuVwf8366X+NiwQMqZR7t1lb85yPd5+IvuARV0XeBCQq5n1tJZPU2RQTolxEb6i4lEE+fzuHwJb7L3SsNVJIAB8k/zWUZs6xKBaskhvCL+SIQPfVxChH/uoF9cA55+vpvubKP15SzHSi
  template:
    metadata:
      name: r2-pg-backup
      namespace: pokopia-wiki
    type: Opaque
