---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pokopia-wiki-pg-wiki-credentials
  namespace: pokopia-wiki
spec:
  encryptedData:
    password: AgA7D9L3EN0A4gCl8zWFkt5jzazJ+pDzzmQbCLHnmtPONU6PUN8uan3DyppjdD9AgygbHeANz6j5PH5sHvFI9qqrFJaogrYyyAx62HODyG+08Sms4SfQEfwqawcuCvtzMkr4iylTppEM3J7Mxm1XdHQfggIS+L/4mj5SsiTdEcqSOJE/BeCKNlh1kxpPDuWMdS8IPVO58rBcKO83TySyiCIda36Nyl5WRv14dity/e9ZbtVY1CZXqsq7lB4J9LVhyXLGLnAj+gyPX93PKWIBpvY13d/4WZmacDTljKWpjMyRsHHPPEtWcdAoc1SI0lKqlFBKA8yK5oDNIZ4AqGF8F+Vvnw9BrKa7GgcHyhaOb0iDde+JBI6I0ZxGhwMLXOVzFmE3/YVG4j1ToPxoocvO8qmiK/IJmyTEjWHUBvGKkImmg960Obsz6Q9b9YAb+1+iW04GK3OnYGlHtYV6FIx2AwhitLVvIV9HnSAJPfZg3cRHuqA3AgKyegXh9khieIIJhLYc+03KcOjtn9kwQR0hrpMmPlO64jCyqp69WwUsp2uTPz+4bVi+1x8aaxPy16UxUB/sYITUXOqB5N1uc37JJySnnR4sBUC/NsjucC6AB8u4DvX4MZ3Cq2KmqI8lcDOS8I+gi5wxY3aUUmVsc0YhyqoxPytAmohJ+pVH/vP05qAQffFo4S4OkMvmDo0A0oxFUJ6p6rt75JkT37N7ouWlxV9pWy3LNDRW5dJfAenLlfRP9A==
    username: AgCJI/vO4qZBwTEAnzfKXVhdXFlxkunFCCaDMCJQETtCWQ6UfXrJAs2Z/BPXHylrCj0uhXKtosYOkYsSNjUBXEkaxkE9XX+gcSQynDjljDNJrr4nJbNJoRsAWDaj42q1MNHkjcMZ6KqaYpsd1xmRzR2YOuNaGpOJoMK4izeChYlYJ6xtzYiknnmXUGDVMcypflHcOoC10s7+CQq57LhWfSmRTyV2m0j+9vtLhW7kfgGxVoWa81chXQwCx8jqEZ9lelC9KrZPABykBi2H8xMUZ2SjOFfshkYl3Jt4glx598VWeGn0H8pLlRfpnzERF0hIL3SmiB+J+MZDN4VEGyBzMfFnG3liLbx9WXf0XTRc3+wAFNPfLoc3gOYvQXWbCSrbVk/28udLkGv6g7eS29wv6QGi7/jWqlCcD6OMVPt0JG9lBeZQwGXZifg8BXONCUxgcP1gRjQocWdEplgFa30DL6blqeHaJ38KvXsXUY/pE8dG1uD7XBI7XmjNnlVaAsnLUb4JJakvqmjL/mgRGevDPXH9Sjg/pbzryLhF8w31Nm681gv5QborhmdxipFtQoZ9v5zsOAzC9uCsVjr8B9w64sXdmLPLj7KtFW1yEUVKnPkfU7WWaiGNmUTBfgJU+4xUw4P5CN7BcMF/kAxofU6TpbNcm/yGzpCT3udWXj3VEcWtvWcUgVStFkfTyTN3MibwOgnzh4de
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: pokopia-wiki-pg-wiki-credentials
      namespace: pokopia-wiki
    type: kubernetes.io/basic-auth
