---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pokopia-wiki-pg-api-credentials
  namespace: pokopia-wiki
spec:
  encryptedData:
    password: AgCJC7ke5mPeDv0NL4hAZi3cAHbtqUMtsV1uW2ao7DXtV6Z/NcAbJyZWoE866ZDMwr0JuOHIjIjixt+Ois1dXg1S1CdMGMIXtXYCRLO+9yWDgtvf9y3kTDBtq+NC7xoGLWU+zsI3SMN84YZofknW1CYoCKU3FOYTMALmEjKSBPQFTJFSdDzk4Bi9gdcGylZDHj0SLNkOFjrGwyjQDbggWhDXCM7CfEyoms3XQSp+QMUbrkzb6pGliX/dGBh4T6uOZrVYMPF9Bu08zi1JUTH6MzSrnsMfu7hHPbF5k8vsE7mucy5t9xlR2GL7Qqg11FfT/wtXe+zkRg0DpOA7i0j0p6A0STtj+n58KQdtOkjYS+/wiwHdEGtziRWc3XleOKba4TBhO4XXPtlBhaviHuT9ZvBh6fe8cZ6lmhUm4GKcv3h5LDbrqrql8ltRr3Fyc5vcXitUiXRcRmD94wmyok6bYoMU2CKyyZrdEmxIkM1P6117GHum1kWfmSd4UekvrqINm0xWnw+2fZz/AOKkH+V4w8YuajKE2lZoKztRmdcbMUZy2NWjOcZXz/wA7AfXVRooxZCvaxColEZXNu7JLEWDNX/+Zx+LygopsQCi0wnfIbIv/Hh2x/gLmYf/Kf42JbiSKctHxbWRlxJMfj0hoMkRMk2I3LOjFArglVSyDgZ96xREh4hcGgRz3ccJs8m+cyAnEt9Lrx4N3CJnTbCn2zRGHgBmxlYX0RZ18XKs8+uEyp+XtA==
    username: AgAd5fatNObU2ReyS1wihflUsD3tqU7DPKeMGTxOGv6rz4v7lFDS0QBILoEPGp5RIWtEgPBZ67BVDyQeCp25gghl9Yk7uoq7+ZDyMMTRJ6ita5fS9BmPSGz+gGmSZUabtpZmncDe/f2owakHC3+s9xRLddMOF2DtJc3mOqxdHVherb7Ra+30OVWogOyDsDIizKnX7pq5aoD964XqJp+OCOQfjdHMd/NVIe1q+DBYWM7FPfZ0ShGlZH1COMiZgyiAMJ+KJT8ql+qVp+PYuiF5jXZpB5Z7snIQw5fFCLW6kCJH1YIZG4MgChneUd4vh1Id2kYbqLLCg1isESRmoUJseYaVs8ZmzmHvEXupxxx94nDt0Iz/z/L9ZDJKHJ37gDt5LP3X6pnMnyDnsPwN9FVa1aPm/qXzZDSH3cgGVQvBC4VvM5qiGWPlHMX7raLRExXhnkGcgV2szA0BEp/tZVGpdT+7WsdZpOFAmCuXxiJJRbnyxuOiEH1mW17fT4bVwdHYbyUT0lsCExutO2VDwx+xjFnlNMssvJKECzwY/uyVsQ3KEDeYxxB9M2V2ifW0eHNzUhhFn3O2rpoGWAHoSEYI01zIGVjPVNrYFJzCb3p550XPXfWGh5K9kuyV71pmtLsX96HQh/n57F34Zw4kS2nQk3atzvVcIkSpqlOhXvAX5gFNqiGHZKwxy/jyfz+sQyq+pIGBZCI=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: pokopia-wiki-pg-api-credentials
      namespace: pokopia-wiki
    type: kubernetes.io/basic-auth
