apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: test-phase3b
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: test-phase3b
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: test-phase3b
  ports:
    - port: 3000
      targetPort: 3000
