---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apps-secrets
  namespace: apps
spec:
  encryptedData:
    ADGUARD_PASSWORD: AgCsmrj6DUD+hx2w6nS9m6ECjPVN0nMRrliGlLYRH96l4Ua5GzyiDHQmRGz325P7ZokfmPofruzlqjrYbru/F5sDUZYP8rWS/lhbKmtGwgIlgOTxhIwAhJSo21i7shrfIEuJBdziNPUXnjX/+TbI5R06c/OQOBHF42kaX6If/0lsihIsSqQQotz70LSSg/xIC8QxqY4ObyyR2CLrovBE9BM2LPC9RRJmnUXrOJ3r/v0f0qFO0ZqmEt91KOua0Cee1glCe9ruzJdDD75J6rHyEuJcMhoozfPMhMWNYSVDgY0Cy1QCrO52dMbg5rwKi1FZ4VpYQGMQqyIZNAG3WQclGwzYQnLE2QsOuCHurvX8kAXd8DbNRiCSLenkDqKghwOuDl4epfJKKQ9COQ/Ii1vlbzG5yRMNq2zE0W9ELXqLTo9FTcliSnS2P3wgYfoZJXMbAK7LaL5zta6B9xkypWfNKtA42P3eSsCcqqgY/axdO9UImN24nPoqkynFwQ0qWer6ncG4CNjCjD4+hkOX1K4+801VPG0wuUEVOwUWUDZevakX2jyw1XN5XBYg6Jk3ST/bo1duEPMZLlgjceSDsbXVj2+S2HD9fYOPIZkMx/E6W3/+5DGuPZcvmcYTjZGKsTgF50naq9QFulYerzJvpzVTzJYCGj17rL+Hgcgfh1zDOrSC8TPOhi6epr5KLyrPZyHK2yF+VNfQRaziAXkdvxsn2w==
    ADGUARD_USERNAME: AgBG3EtBdFC2MXll6VSygeFueNH+8JQ59iFA7CBjLy1HL3fj6iT9pQICCXdsbnT3PzW1p0MzIy+wfaY+GiwdsBF6CnC4fE7uSGdfLy/XFODr5IQXZrjc6mVnnyzi1M/RsVlEFTK3GhsDNz8MfsMcWSGJJBQyQJ0sE3OX2074rzuTiS3Q9EtI2SmyeBTcBoLA+J9VxQtT/btN2b0r0skpdFhI3O2sVArvcwNwyIAge0mHEP9vwzlJj0juTJ3Lqfh2MJPGJSCUtubHO7bd4UBGs+6sNIuAt7yzlNuSxakRPy7Dapj0JLsfa/05D5SegUlznT9NxGE0quA9MLKL+8a++9PZ+Iv6tYBkwFUfdVabHd6G5JuakiDpOd70ucDRbDeeYQfR9CJvkl7ppwkOnmO0LYdgLhBF28Q1AZpjno+sVe1GPKQ8MDp4p+DBu9sjB61gjp8oTxJpYDvlHg1xIXhdQRNRoNFQNrT/KISroP46KQmURYOivbCaGs//3raIztpNpTEXbSWIDF2aUiJMUI4zpGrB3aEDN7tMGeiPULZym+wJF3Y7R+42it6vY1ydAN+6Hd5fuw6p3mym/+8454FJc8qlC4ATZ2JYAgOCAeO3bumEaLhCKk7PWidByjs+TzCQH21CZVEQkQt6MXpF76mxVLX1SlSZI4iK/Q4bg+XSkMz2QHdHimjXp+aYB+U4mQ7+D8yqjCD3uXw=
  template:
    metadata:
      name: apps-secrets
      namespace: apps
