apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - server.yaml
  - ml.yaml
  - ingressroute.yaml
  - network-policy.yaml
  - backup-cronjob.yaml
