apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
