apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: photo-library
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`photos.ukkiee.dev`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: traefik-system
        - name: rate-limit
          namespace: traefik-system
      services:
        - name: immich-server
          port: 2283
