apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-media-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: photo-library
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 1400Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Volumes/ukkiee/immich
    type: Directory
  claimRef:
    name: immich-media
    namespace: immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-backup-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: photo-library
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 350Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Volumes/ukkiee/backups
    type: Directory
  claimRef:
    name: immich-backup
    namespace: immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: photo-library
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/immich-postgres
    type: DirectoryOrCreate
  claimRef:
    name: immich-postgres
    namespace: immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-cache-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: photo-library
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/immich-ml-cache
    type: DirectoryOrCreate
  claimRef:
    name: immich-ml-cache
    namespace: immich
