---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-managed-monitoring
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgAmVGi4nP8bQZFjBOgYL+Mj3ZVUNs+0XcZbXAwMcSicLUmr00L9wMY0yJQmIe5fc948exgvRpmGCd3YvOWx6PiJLZpeO0K1W6Oa9PYXCBZI9HYL7CAwhNK+HRrsBMkC0iy5M8dFJST0t/YU8CN0QGAIrd3Ing4WOw5zARr8L8kOYlUGtXhpz1/TD+hhNbBJ3m5zEDpo3stBcWG8Z9XaXN+hCaXp+ShZEcVsHaJpzBBk6DSZzrYzVHnggSQ65vjpFo+e4uRdbhMB5KLG5ngPMtXPyPutio1G+/8JRb9ZFt32haD2pW/f3oncDQUQaJatiA9V0DfB7Y7e77PMYSBig8NCybk5v42vhvyJOS/0ERxcvalLxLNTGWEnEeGhaJr9VyPV6iWqXPKx8WxfoyYUq6EMeIoWPdbxpqL1WJbDpyOBHkkldx80n5f3yhd87yHZHk7rJ9QcwH+l2VhIvO9YAEp4XevI75h8tz8m4dnrPR9+l4zeBPBoSLv3U7Ih6P9VOx8Po0tVVmw2oYIdDIJzEWR4hp7NXBLulEQ+f5anwwWOw9yV/rjo6kFZemaPBwz04L+CCjV/yIbP6U5Aiz8YtjSt4bPrHQVKnylj9PB0OdpRniQUFDGhzyMxCZkXxOMRtYKsrMYnfzBKI+8Lm6DgPXnC5MPHS8zs8oHwX+d0kbHdr6HA/Gpv/h7DKC0jr/zhu8ZOae3V6R8lLwvyRuhvSSu+4gsMegngOeo=
    GRAFANA_ADMIN_USERNAME: AgCipZtdQ9bvzbnLw66hQs7IS6shPfyLyy0aIu60m97k9Krq4hRFx9xrbN07P0micnmGSnIBhv+vPWezlAzUlLmYg+06s8tBQgHf56sqlaqi2FJjdbxxmi1fGCooTB9XAzE7KO12Dmje2xBBWGblqdbSQljC0hNQoFWp6t/jxR6bSqNd/+sgKsyXfuK41a9CHb0vxuIFzOgzB3CbAgiYd26pUS0egfCsySGt5nQiDDwQrYT/bTkryj1ZcI20nIAZRwkdv24yuAEx8MIjwl0H30+LiSb8h/9eehK05OL6gJQNXp8k1wm732awqNAfAGusXsGrqSYczF1lyvWXXUA9S6JTnlLksTshGOKrITOlUKKtzElv9U+irAew8ws3h2+3cm7V0kAT1SxxDD0Ax3brU43kKNzUiwLl30gK8ZdRwzHK/sRoPiH46ElVOaihHa7F+e558Wv2z9Nf/AmsxbiEGNVbrEvajrKeXJ8nn1yrFApL79A2vXPSedR/60kGqEk7M3yNY4nrtkJcsHtViYQKzcg7Jmxia+/3UdXM/0brPlUiWNJ8ps8hAkjemaxUq40jgoS66MBH9quZVggOWE6L/vtNI0Z01uphAVi+4hc3GsJyAtUtsOT5dlTqpeHLuEhok/IgZGeQKyVfvjClprUOvEvUFWfHRbpJHXp9sM96ZwRryDmqPoQEBDLOsNf1yBEjunqUYWWDok0=
  template:
    metadata:
      name: infisical-managed-monitoring
      namespace: monitoring
