---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgA6CVD5QzIYuvaL4hgLEsKkJH4WCVNYFd+mftmhC4EUIblMaor4WyZvvjz7BAfi/AhNsqoTiIvtiONNQxLr+CL+gtp+zv1Pu2WOKmmj8Rig6ZURrgVRk75Lfk59QcfztHB1ELsIctvA8JUijtWS4LWSuoe1u/wRzaLHmAO/FF3U7Nivy6aXH0gXnvWX1vJDZnK7ScEB5UV5qP8+Qp1zbXFX1REEu4rQh4eEXRPrEIxjcOYUggvwzDejwGReHVAUqjNWlccjI+gU5omJ20N3DDNyxNudmLzMqEhMw9jmoICfJmHf6ZDwquvCq89FwJdrJ5t81NSQKG8NErlDO7jFXBKE9SvTzBbVys+XlLyHgKxdWKW/6ngXpXzKOeVU9gqv1q5liplZT7oHZ7PSEu4l2CbCBHDdhlgUlUplwhBtMq3HBvUO6S2QwEMQpaBDWF7m1wstxiyeJuc1WJfkfX/VFlrbEk/DU0AlqrWAbjUr/kwDo6bR2VKoOeHOu5aO9rekIoqJMrFoMYkdswZtsnWoBzAnCdRdgJGAK8Br9Qfn+7U3yXuEgKXxDRnxn0jJjLSqRWphbkxLyDdEav6rR2Ld9pTSHhXU6lT6qg7gRTaRXOJRR0qUo1hNdQiVE5rAAxUTbfiKRf29deuUsykcohQMwWn3hSpnK3nOOoHfa+NbTC7/7V2ksNl3bG6Kkk3pYroRPotm+rQWaxBA2RmVdK31a+jbgseW4CKkm8E=
    GRAFANA_ADMIN_USERNAME: AgCqFqUKD41E9SkvECqnY+tP+y1FYFWOjtTpk4nzf573yph0LB3H5LqxhIWNMOJ92kJL7MrBkGysBaBqv37icEkWR3pZwtGhCbeDEGvecIau/OtESbkoyJirJ+PgbJpN+bedC03w9GBZTHRIWrRCRMqWJP5W75aM3BqSqwDJmiPOE5Hc9KecMwKIbWxKARqG2eUCWpO+16TV5hmgZmwOl9Kgqr2g7b6CfzBp1DsmaHOAXl/BlTLqWtYrtTf9i3p9TkLyPERQ5tPC3Z9FWNyY1kdz3W52xAbLkjihb3Nbi4Uzl+HLUsaXFUh5dZRUL3PTpYVHyAYSVHx47lC/VzR99CipzVCx1K88h02PQ+Mgwkyp6SaiG9CdKP5M2BlX/HwxqpJ1gfKf9fZGOAHwDQqEfqu6WAgGmpo7Asw3OiB1cTXE+UEbLh2VCJK5U/YlR/kX50uz2rhdxy+HkesdrxhSKQ69I/W64uMtomDQWGkSQqNSjC3mp2YLlb5xxNBwZVbFnQfnphODNiGXUMqjlY3jKCFSRQ2D0oNkdVHPZrriC5jGr2lZbAPPrz905nyEKEp4Gag/dlXLnYZ7GgLQcVOOEz7K5pb5pqSu6u+wdRaLM/991BnSCWwDrD1yrXBJyxxFbByr2xfS3xMj18TElEm1s5jXc01pVtmEL2TR2uhUkfsVc8lIoWWvNzNK240imVt2jAW9U18yq7o=
  template:
    metadata:
      name: monitoring-secrets
      namespace: monitoring
