---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgBYqve3srUVFAetL+WuE7Uj3p9kRd15IpuEb9lIKQQ3Cj9gReJ+WZggJeIsw7XSjDDVl03AE/7aVtaWhfTlfiX1LgVOiq4up4XnBtI/nGNgd0n5Khe9ttbv7STuG0t4hvTGDxK3o/pP608+bbWCtPSXZobZ16jWW5uGYBbicsf9Ya89JQ4TKFZeiMqS+mwQjpH7t8ywV92iJzSxcL9At31ZNsTaxCn+JKE4f0lnUrG1X7oG9PobENl2uskLHxcW0plOXBqW6nUqO9OW+Z4XG51YZdXFKmtNuGZFWK2E5/hHVjL4BOIYEqPqGIboOH4iIdag0Ay65QI5EKvKjWLCmnsgW1sIwi8uFyfhQmZm+xtHcrMxTToO0Qsx3cv+VnRA+Xh3DAvbHoO02YQGVORiqr5g3QmManVoGoXRAVBI/zqGB8d/pisZmCmhpBYY68l9szE4i9DJjTshqrC+vu8hh6pF3vRx1Ih7astkH7EueWV1ms+5OKyPrrm6NNKboApqYRYpOVECy49HleGQPhk6L4gLTFAuV9kZEHqS3zZ2qYcxYa0sgt1GJiCgvG+N+mieV47gZvBOWKlzyC/MyENqgiWt3QNhkxpJdKT1L5dV/3Y5LkeNxBAtl/6ait8/JS3cqj3j1JCJD+w8Lav0BJ1X4CPis5uOysLRVlwtOgAAFKkWqA6I0gnfVsxG/xvmEsL0j6Fs1M/g+bhckyMTr8Lfpw==
    GRAFANA_ADMIN_USERNAME: AgCqFqUKD41E9SkvECqnY+tP+y1FYFWOjtTpk4nzf573yph0LB3H5LqxhIWNMOJ92kJL7MrBkGysBaBqv37icEkWR3pZwtGhCbeDEGvecIau/OtESbkoyJirJ+PgbJpN+bedC03w9GBZTHRIWrRCRMqWJP5W75aM3BqSqwDJmiPOE5Hc9KecMwKIbWxKARqG2eUCWpO+16TV5hmgZmwOl9Kgqr2g7b6CfzBp1DsmaHOAXl/BlTLqWtYrtTf9i3p9TkLyPERQ5tPC3Z9FWNyY1kdz3W52xAbLkjihb3Nbi4Uzl+HLUsaXFUh5dZRUL3PTpYVHyAYSVHx47lC/VzR99CipzVCx1K88h02PQ+Mgwkyp6SaiG9CdKP5M2BlX/HwxqpJ1gfKf9fZGOAHwDQqEfqu6WAgGmpo7Asw3OiB1cTXE+UEbLh2VCJK5U/YlR/kX50uz2rhdxy+HkesdrxhSKQ69I/W64uMtomDQWGkSQqNSjC3mp2YLlb5xxNBwZVbFnQfnphODNiGXUMqjlY3jKCFSRQ2D0oNkdVHPZrriC5jGr2lZbAPPrz905nyEKEp4Gag/dlXLnYZ7GgLQcVOOEz7K5pb5pqSu6u+wdRaLM/991BnSCWwDrD1yrXBJyxxFbByr2xfS3xMj18TElEm1s5jXc01pVtmEL2TR2uhUkfsVc8lIoWWvNzNK240imVt2jAW9U18yq7o=
  template:
    metadata:
      name: monitoring-secrets
      namespace: monitoring
