---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    BOT_TOKEN: AgA8xnu9k7iE6i+TBh2dVkb8wCyGIoxOpj1HgmaoWkSp/tPwFRPuIKdG32ttUvDfw3nKSZ16vu+yV6QIpLsQDG0pubY9lRF1nt6s5WPHqZu/ubBtR5PU0nOLiYpX2HY7IfAKuW7cBDDmo7r+IdRG0Mwsu0wXz0YTNzytTZWTQGXGZSthQDsD7xeyaIiXeUqZAsI18p8YdEPgarbXF7FanGRDXX3sH0cU8Qm9VQdcmYtt6rfJgkztq4B+0wlaSglo49pMCU4E91Uh55+gfifepnQ+3pNq5T96d1H9WXkeCI7jZMqnwbyPh862MjDZrfZmiPaSUh9VVTNk5YEVV8Txv/QeMnv5eVIRi11Yog9ekVZBBemJD5/OZIQHiBokTR71uwBdk6z0WCXr0zPf0KxVW1nW9ooclejVsdjzpdXFpB6AUhxVcrRs62seqlBeA9MZCk9Hm/eHvxQzf62lr2rp2DL4bHNXM2jeSA9wHAMgHPJJWCpWELDm5TqLxO66iCnalQ5r6rYGeU2agl/Qby9ycs7PTVQXV+/fBIMAU3dH6K9KDu4m9q++bAsawubgGxopXmt+NMQomFY6hV5O2hBTbjWfslisQSNRQ7zKP8afIFiP6iGERXPuKPwUU2LBZDoaM0/FyJG2C2Rt3Hi5mkb4WWn48UMv4iwZPB/kgTiMyGtTCeWVXS/MvNwUNjF+ZubqZsZAgGGtefYeco3RVsgRSZOcK9noGXX8i6w7vh/IWyoCXoirpB+nYBx3GO4YPBTM
    CHAT_ID: AgAGkG/2q98XMTvcYbgsK7jMGtE+BUUNi+yTSQDZPjWq23Ibx5x7EBUfMkhIyO2BXPkcjHeywsbaUV3i2fHUIFA9KL2bBXXvZilyhKn+6tOZVGCSIdtXL32mvbc7jTMk9z3xEoT5LV0utZiDinNwUlVzvpPobU7CFqrrATUbx7qRqwwZe5371E5ZtbZ/ojHRtmlStXhNl7ut3kFXQXur4V/bPa9BCrvKEDLDYzK+EGBBUb2uBq/NUWm+ZuCYDyWwNOD+bMxKMm243jTfpjj2GV280oHt7V/tMwosi39f89gezkuMUOSR/MDNMSRZKV+3967ot8Oloy0clRIFl5FiMCtq41lA/4LHWkXFJveS91yZLBtmwrQw/LWaCMcnA/iAzA8l7iObka6pS0zF07b+juApSwcbpEFge49Y1Gfnyc05Ji3mt8kwEyKaM/qaH1ErpuRfWNhesGzGUpbVt2+FvcrFIMZDH/7SPexlo4ryZ03QPi+6cx6mcyFPfJFZgPR+Ihe9MhrNkjcY8KqStUd94mF+Lm16gdvQybdqvWIZFb+Jgy7Si2UcwONlb0Cij1mVLIzqeuYR8/tcyJGFltoIhH4duZXyKWKM2mc522BBHu3Q1dlUydQwqmk661A+6eet6GUT+TRjo2JLco7JBECPE6EjNuCD5vnfdHhzAi78OjI4metrOyVyxrmHl5BhXwhOnkX1WiBTsMVq64gD
  template:
    metadata:
      name: telegram-secret
      namespace: monitoring
