---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBWo8tTDuQ4z9UXZYCvSzu3PEEVT814+4+dv5qCVTArwOixuyDsQqQ1E/6p9exP2ZZuoDTY51yrTmAwMKDxsNzzUG2ks9Ja57PJSMdN5EtUxc733wMKwtGa5x02NJnGJpiTcacrtr7EmXFUeXLAwNojLmsiMP1UOjCUa6DD253Pb3vvLNZLuzZGnSY2ljaEsV/pvQdzNqRfwSMAMz8gpc3bVKPfglXTm0op5lJNgyh18K7qRAxM5saLNEkOJmMGPQ1j0SFzfcUcAdriD8CHGege9XtbW08BUwKF4DUifQENvD81k5mi66EF0uX5hkz1+xuY0g/lfRPT9fhQ7v43/NzS235598fyT+DaJVixAnPTRHDozeWeHHJlwWzjdxLsv8/d+bo5QafFg8ZEVEWK1AQ2c2KV4GzOA506+gyyl58cv3dEsyytp1shnFRMcwa498bsG27g9gwfT/JmgyW8XXPnmjUg4OgiIfzDAGHs8/iJJMBN0Qhg6vkiRanvgc+lI339A+0GFGI2e58sD1tTtdJLHLmKeJ0SfJULGM9x71zj2WFiZ598qxF6OmMhQ2yczaC051cfzilL2d8jbtLBfNaUgqGMBv/E5Sgodx2ZufTtL+5X2AZta2CM0iRJBhcqz1vx5yUQDVla+Gj0mTF8PnDrRrpd4SlzGbF77bwRPPJf/kX2sMkUVB89cyYhvdQqXvi2VmCNCfPetukQKxT5jOubpeTxoZLoC/eCeq+3XwxzjJrf7WLdpTkU8z92xWTh
    chat-id: AgAshPUfUgSvWRQWWo85JJkavTSgrjqXezhWblIZg43uqFLm9sIk1cjrredFt0/FfGFi9Z1ST7bM+VS5yDCoSrkSpezIG/vK/4YnhRbvTb/wHIKu4+LEM3x//4BkrNqhbYqD+YTd4FJnELu2e3yx5ETb7hHIildb1JTdPWsgh+J3FzDgDEmlIgAaTViMfhY30zmgfRqIXU21OFGsNuqchh1gBUB88mQRtZexUzL0hE7+iu98EwTTMMJ8dXp76PINuxUTMNQ5CNfV/y+J2PNaUhLpdQZess5gHjvFRh+UguhKS1UUfUMJgbXf1iAbarKc+uDm0SEpgzGoO5MXTVTXANgR9ZDCA3uLwHoYSVFWKobVJdft9EH9wh3daKQkB6K6NTCNJc3mu+6g+bx6McKi5/aM+YOlzOuCPMuXgEdmo3y2vXjImwav14zxakDo8L1jYu66+H09iLSIueLkzdDTiduqmpYwV6560Qyiw0qRKoaMA+yRzV69+kguZHiGd5YrBZl+jQXo7HUSdG7Dmjy0QxOp6vO0jqUvUZpYK3xvdefuGZjszydeno93u3HQ604rhrBvCRQIiV+JNnhk1kNaBLTOj7pujOJlC7jMt3vK1oQSRkUaWnHbwgSU22IeBhZTaEk3b4kq0q6VsDtzPwrFr9FLA9Joij02diBTruDmtRAcg5Pj80tqN6F+f6HbW/ZfcQYWR64AI2a85mtx
  template:
    metadata:
      name: telegram-secret
      namespace: monitoring
