apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: apps
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: management
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: portainer
  ports:
    - name: http
      port: 9000
      targetPort: http
