apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test-app
  labels:
    app.kubernetes.io/name: test-app
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Apps"
    gethomepage.dev/name: "test-app"
    gethomepage.dev/icon: "mdi-application"
    gethomepage.dev/href: "https://test-app.ukkiee.dev"
    gethomepage.dev/description: "test-app"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=test-app"
spec:
  selector:
    app.kubernetes.io/name: test-app
  ports:
    - port: 3000
      targetPort: 3000
