        apiVersion: v1
        kind: Service
        metadata:
          name: test-app
          namespace: test-app
          labels:
            app.kubernetes.io/name: test-app
        spec:
          selector:
            app.kubernetes.io/name: test-app
          ports:
            - port: 3000
              targetPort: 3000
