apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: victoria-metrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      protocol: TCP
