apiVersion: v1
kind: Service
metadata:
  name: adguard-tailscale
  namespace: apps
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/component: dns
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
  annotations:
    tailscale.com/hostname: "adguard-dns"
    tailscale.com/proxy-class: "default-proxy"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: adguard
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
