apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  encryptedData:
    kv-api-token: AgBH2AjuSCYAexvbFtr40vyFoZeF3HhAF2xhxvb1kfqfp88wAtfPfwNFnRai+q0fdfSExN5ecwAjE68dVqMOttCHlIFu0O9/kWHHBgqQ3Kezh5VcLPc2VcFOyoUn72ajHNyubCm0j5j0sew+BXob8doJz4bZREPm8MxkQyvavmWbVMswzJdD1GO47/vFYYlG5qIewv1rtHsnBGZCs30QQj8LuxSBbhVQlbTmirKjPSt+meKK7BvhmbtVpCM051eBjitsrvD+NFpdwxUih98v2Y5iFftpz3j74IXrJfMXMJk+/wSyr0koavlR/PRvSPypmf/yWlN6E3IX32G0nc6T07Vuswa3ZdWiFfzoUlTvH4mh5zqqCBNYlqpwfqRHTkNamtIQ3y/DCDp47rnkm75S7zAfrR43GW0LUDyRuepJu7mg0zxV4Mf1x/qBBcN4eUPU5CMuGUs/TXzo+tvCVi5Q0Wcjll3JzxC5mwD/FYczxpxpcj6310bTYL8GmlSXVXza8TVSe7mke+UWADCqlwOtoeGynK3EGdBUMSRl4VyvOHjMEPvjhq/DbNXfNQfYvRgDBtJN6gf8ORhdDbs/cP3gT+phyvegkwhBynKPN+Pu8weseofxNDH4XSx7po/7EilHk/qViLLcXgWr5ZnkoYFO72sxO932s7gUpCJQkBNJvxPpbx4LO+P4nrjwTA2iDx1GuaY8TMrdlVNUUTH2OtrSpLVQ7p+NPII7EzlGOWzgsyFPI5JC2iH5bgxl
  template:
    metadata:
      name: traefik
      namespace: traefik-system
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: argocd
    type: Opaque
