---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-pg-backup
  namespace: pg-trial
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCiqvN86AHwY5CGhXfb65ol1t6X8E4qpWf+jWynJon42dhQ+jOb6oYy9kWZqiWhfcKvg9L3U1FkUHG5lW40ftFOjcbml0BZhLjnUL6H/35VCVE7qsz0i+V5eYLMgiwOmk/pUYwOSe2sDc9/TuxzFg6TT0TS2bsBVFXZx+vQ/oqkj+PCmSZv5Ui599FiFz4oRLzwWh6APT2fjHSmIUiv1Lks4EUaSrhiGE0cpul/B7bt3hdTpWfBtZ4hC9cnWIPkjbeexVupnvlOHq9FOr0uUsoTODOoVB5ZwMeWCOf0J6oJSjn/Hag3lUBI6BYYqdYJL8sgY66hoya6xgDCO8ivGkca5ehVtqdxeiJyg1iDdR+YFbJFHDqMz/j+xyVZACAooJbfCAkEEbLn38Aa3eL0qTeD76/FLfZ2iAQaEM4RVaX5BQn8ehb4zlv1uVV0REJnda/t/DnhHKFzzVV3gfEsVULbsx11Mdfv/HIsGc9/nZK25/jB9OQzpVwlbZGXrDcniXqetaeLlAzq9LTD60MGTzCy0yhT4vaZUHZF1uMq7eYgUXSoC8X2Zi2U2Py4gWyhXV22U9iHkPedN76bJZUxaY+Hiy7zRLx64gaDEauexPt6aBg83rsehmlBYGjPIAt7pZ9S4sCfhZ3eJJPwsw74Kds9bOImGrrYfpv/CfUlysOlXbLqYthD/KqdLu611ko4UkWucQ1wU1cjWN3xF3dIvr9BbFyJQYLuEjCLri2eofuYkA==
    SECRET_ACCESS_KEY: AgCI8tajfOFvzPi6zVigRKN7xp0gBIr/MYGkgtwlxVAu3DWla68cWluNtybIPF49drBMkwdToi4PIPMWw8+3G1nulVHBg0P3FBUm6lVf7GjZxaLwya4ApVQNoR1WcF3OvTrz5DGCN/ktJQjQmve8sUoaWVYVeNq5JipL5EBYSwN8/lLXPD0eJRamlpFreIXabJuXDjg0ioSN0F75ZWf/lTk6g/e1hTUa0YjRlwd1gjAg3fG0gxvJVHmPxxHidX2KwujZ8ZQMod91zKXFVLUXSPDnbGHoFQXIqCj9AmLQu/7xjib1CNpNkUnNqBFBcUK7iIDrrihGdrLx/kZso/TZvY9KDjcX3XGtr0wA+nYpYZ8GvphLQQR71LP1tPUl/+EyNhyAF5+B8CCv+S9JtkC5zBSp7CLItC1KhQxXOZkRI1NG6aItEGPOe8UMCkASipRY7eMax0Ur8KDByxjw81nmOAj7fErrxxykCCJR2DSxTR84VCmH4RO3e2YDs2wQAYVuYVoMSSD67jkeicylfFTdc/nXB/mqVp2XYtULpPsQvB4ACcuELvg5j/GXsKZ6aEaTtdCoxh3M0uy+IjJTDvbyMTTeNIYKMJc6/gcTPZwyc7fXYwVEISnzUGhslDGZ3arPNFmbfya05oToC3ORbn64CWtHuzbRYSv73F9IFU6VUEmZrBqfH3Uzm7/Y/frFjQ0D8FIReMfMfBrrZjJuwkE67eo8aYdqSnXM/liJDu6zdU83XmjG2FdM2lza4BpiD3MKWD9mAopLtFeUR7j9Y3h+ANyR
  template:
    metadata:
      name: r2-pg-backup
      namespace: pg-trial
    type: Opaque
