---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-trial-pg-demo-credentials
  namespace: pg-trial
spec:
  encryptedData:
    password: AgCG5WHxZjz5DrwI3Ev1ooRmbpHaGdUOzkoJQLrL8NrbG8zT/tRjDU/i8vOMcKK6rZNOJTGsIIbyzesLSLjsCHPyXBO7J6m1hQI73M6Sh6yMHqi39TybCMP6yIx8sP8ghhC2AelKnzFmuxamlFUysFjSuPXVqyT9KhtOFgJPkBsUpOiZZcbfs3GvWzDHO92wcl0zbzKBPOYQjyuFwXWbc3TzPSsxTjWFld88CvfIgjEv1DgKkllkJqU6hJXvvoDfkq6f3Yi5CcZSDAOws95nT+SQSR9FHvUbs5XOLOHj6lsm5C/bm3h3j5Us38PX+O0kRE2BcR06eKv/OewTDxBsh2KJ3yc7ZoEl4DZZ53vdhfDqc3RBb++6rL+pwR89E6TZwhmT3dA0TSSAOrHTmursJiRfcm+b1WPJsweBbwyLZPXHbwg7UIK1irYA47WnXt3osw4aC7L1CF4rtQGmfOy5j2zsX1WlVevKfjl8XgIMsrM9WJikyescUFELIaFUZwx+FUA7oFn5wJ7pSKqwGohjQhY6j9CSo0vC/0R5EhXoRfRu9ffp+o8E/p43rJKNxvuxy2ikkBXBkFtjdZGQKyZIyEMeL53kuCv93OZVbqOuYCCO+TjViuo9yY4hUCjK/k4134ZhByUt7pJmn4sInnW07YGV4nxgIbOaA2WftupIdbTBrilomak0tfWvMMTce6O5A9YEIU7KBBl7fulBeCl+9Wd6OELGGt0JYHm+xy0hFlyXKA==
    username: AgARwB8sK9txyyr9I8C0t5hw+ekI5QgGNLii8NxXioznbdZTmmQGyqTRIUUi8Lr/DoiRlbJjJPUDQraGa4Hvhx8z9s6eQXB6ghwBCE4PIKLqKYzpDn4jbv2AAHWxz4BXhA+9EGkHWp/4Zq4IJfyoMPgMLYR8NKva7YgO6VwpEKlbGpAvaJHBhiExmewx2DbDS0n0KRFO7GrD/etTrBbkwUcVKO/j6E4a4fYohuAOszK1lsWo+7h0cRbNms98+MYWImPBkoO5YyZHRm5AVLlSBEnVOnQ2o5XenPPc7+F7y9Kd25K8nU1t/+GhdUoBYKSjHIucAUWvamLt5zPzZ2DM+xgDcbS2yGeZXohhSxzDxrkgE3pk/qoX7XTLowks/ECHBcqJLQyQdTfTc5aIdezcOKUl6OWKXk6U2VstbsW4H8mI/Sw2cvnnfTbqmlohqJuDeDOza/FoRBCANgJZv2avifshnZrQ7KT7sigffpLaVvW1qsYvDIwfGkyHx8BJR2Bg9UfBSy6sm1BI+XGT1DaleWBQOECFNwWIxjYAISGXWVd6VJuFjzeXd85KE4sTnUkndRpNmdEJxx+DsihLVmIsPa3H0N9s/l6BhkGbyQURJXaSGpaXq/SEsJff4ggq9lYxjanEuVBEJ7bJjNujrCVajsjzNyMgQo6tfML9T7XDI7K1wDzkGfzG/TpNTd7MJmerQh0H9DVT
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: pg-trial-pg-demo-credentials
      namespace: pg-trial
    type: kubernetes.io/basic-auth
