apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/name: apps
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
