apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dozzle
  namespace: apps
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`logs.ukkiee.dev`)
      kind: Rule
      middlewares:
        - name: tailscale-only
          namespace: traefik-system
        - name: security-headers
          namespace: traefik-system
      services:
        - name: dozzle
          port: 8080
