apiVersion: v1
kind: Service
metadata:
  name: dozzle
  namespace: apps
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: dozzle
  ports:
    - name: http
      port: 8080
      targetPort: http
