apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: adguard
  namespace: apps
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/component: dns
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
