apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-pull-secret
  namespace: template-web
spec:
  encryptedData:
    .dockerconfigjson: AgBAS7c4SJ72+VtWZkToubx6c5wRjBp4moA8Cz2MOn7vCxPHHGN3Lh4AkoOwAglYPYWW4TIjLoe/Kgg9h5ZHbVt+5FEUK83QCxpbBXzFpyqeOeb/QCh/bfPrfoUzZi1AuT9EuJQqR+sn9F0AG85wqgLsXfCF6z8SO9BarAQRmwTsq4si1zt1unogttCeBD+nD/lzSwmW3pVIko8SCSWrqcV0FLsI+XPmRyq+BfqfqDqUU6xqlMrbSG51zjiNNG3CfgbcGokSQrXSJIrhSjSVC/7QJgBg03l0BU9buAuU4WczrQRv33fdjdRt8VhEiSXeH3njA3Ky9bBmCdIAdtxu974ZBh9VjLhJW/LNjjX3fq2rjCsc847UmHDvWyu4zbUwJEPy3gAkE6YapR9Ord8qn7N/YYc2Ykn592RkE8UBcJWd9eX4UOJVZuF6tbIdVVv8jfF/jBv+lCc3x4nQgiXyxDE/M1nEIx3qLwaVOL2mf2VS94JhTVeFhCLVMeqvt3RgbFg+OMdmJ0ytbAcrfSM4rz034jFTobIfjoiR3Gc4eN7mALlr5GNz/IrW8agcertZ9MDoKHG0jR/YbbgPfJao3q3SNmsnuozq6DZDzpXPx6J3mHa9l6LI0SGOq3mYzA7j1vLcgEyIlWywWWw3Oikq1JArpfZpEtn68pDpJI/Srz37w5odPMYoK1jev/YpYczgJ85fK2OzqOOIE3HO00oJBUN2BJt8rB4HoXH/w4jbtQoVXek2u880L2yIp7t71rjFED5NaByUw56iGK+OqfU8qNkOBByKXu8jO+12GmPZdYkBWNehDpaLlxO2VXKBB+YciLIwFdP0ZOHP9vmJ4kSINDGj5ETsWQx7hbIsm/axWvi+wgLSiJlHb8g64EOQRfaAkMX5W7+nPNc1ntqLF1c4nGqCJjQRY9GNhzLR6iE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ghcr-pull-secret
      namespace: template-web
    type: kubernetes.io/dockerconfigjson
