apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: uptime-kuma
  namespace: apps
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
