apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - priority-classes.yaml
  - limitrange-argocd.yaml
  - limitrange-monitoring.yaml
  - limitrange-apps.yaml
  - limitrange-tailscale-system.yaml
  - limitrange-traefik-system.yaml
  - limitrange-networking.yaml
  - resourcequota-argocd.yaml
  - resourcequota-monitoring.yaml
  - resourcequota-apps.yaml
  - resourcequota-tailscale-system.yaml
  - resourcequota-traefik-system.yaml
  - resourcequota-networking.yaml
  - resourcequota-actions-runner-system.yaml
