apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: monitoring
spec:
  limits:
    - type: Container
      default:
        memory: 128Mi
      defaultRequest:
        memory: 32Mi
      max:
        memory: 512Mi
