apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: tailscale-system
spec:
  limits:
    - type: Container
      default:
        memory: 96Mi
      defaultRequest:
        memory: 48Mi
      max:
        memory: 256Mi
