apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: argocd
spec:
  limits:
    - type: Container
      default:
        memory: 128Mi
      defaultRequest:
        memory: 48Mi
      max:
        memory: 1Gi
