apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: test-web
spec:
  limits:
    - type: Container
      default:
        memory: 64Mi
      defaultRequest:
        memory: 32Mi
      max:
        memory: 256Mi
