apiVersion: v1
kind: Service
metadata:
  name: victoria-logs
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-logs
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: victoria-logs
  ports:
    - name: http
      port: 9428
      targetPort: 9428
      protocol: TCP
