---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-pg-backup
  namespace: test-phase3b
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCPGOT/Pku/bmcnPLbZXMpgwmEn9HL/xayAdclREb1SoqosVOgsUXzQ2uEC6rIz+DrPTIFauNyIGNhkH9jhlz26UypdE8yPsz5l1Y+08r++I7vHQZ01/QySswoOMPhmu7OFD/5iX5o4cqnRQsbA9LTnp+Uqm4Vv4c3HvMXj7p2hPMBom7ESwIfyuFdI03K/jnQD8gfSnuhzdH2QIozV/qBhgCjmtxK8Rd6C6pIyczkhwveDkOq2/npOkSf2uhZzMkQwy0VPikhT60EE5kPGTt3y4rPps/Ws6yVVw5h2nNyeL+yQlTVUfK/mJ4yG+6AZ73mo3G1paRH9L6lnyjjZJbHWiUwtvOjfkwSu6D6kYkXRp675f+gxa1BiHbu7TZaRwAIGGDepxZBEx3bJQ6+ZDeAftvdl4hWLE0E8IsxLa6O4ZOTbEC1hH/bMRgdoie8sYZXlmTneEKEH8acF8ht3yLzuHnc2kDG8q09gAUhnPRqyPn5+t4EGCSWSuFP4e6TTGxSU+BQsps63n152KipKECvggjT+n0itujA9TmjYf9PoyIliYvTE5U77pwlmnP7410cpaCREEfzWJCrBMbr+QgwJdVflQlnmIeXtwoaEI8pqj0y1nDEsxvlh9PkbOildITZ3HSXBn+UW3pUe0CpMqBQDul028sEWaeNfTeNUC0jlTp68+5eI4w6ItbVNN8pvCUleso767BT6hcpgjrD7sFYZhAwluxEOUEtQqoY19GcaIg==
    SECRET_ACCESS_KEY: AgCt+OMD0cwuq4abETaykHj/znlKDvKh3IxNdWP2LRkokPW9pRVl1Jrzyf2ZemdRihGav89gLPXLU85XCIDqgdFTMMHuJk9LkN9PYRcYdFwFXntqUI+KMzrWxObCPWaSosKCwaBb5cAIPBrWqS528o7QS22+u2bcqjU9uds6uJk9pCMG4rzRoZODfZIZu757WLqRUvGU7OeSvHD1ruuL4OZ5HN/Wynv6Dk038cVXEmG00bI4It6MwB2YpLgECP2lBmlMNAEupS4e6kXb8UPE3oikiLTiNz/mYjqHaN7Ty+r7sP8eDBzlqapLQNXApWi/rFgy5iKLkn62MB2lmd4vJNpzZQ1x/1M4paDQXpqbbSkTKFHvqoOtmGHnVA95pF7icRdfIlLWPq9yONZcDPTKRTxDHXpNqkfIoYsiBQaOh461dxGXo/cIG4aUxTjP8+H4eL1AWr6ZBJ2P0IiW3BLAKUT/C6rTS7TDSKx8IBGtgBfhLI8THiORFeqnOXSzc+Phk/VQ65TrjCJhvUDlvvWuirgFMnZXYj2wiNLKfpge+hXRYCdqvq78pNoYx0hX9m4cF5FMUhukYDZoGnt56KaLGsy0hbeXN5DeyvbGxrwVTt+M92HQL3kuGErmAkYPIXqXUyFG2b21gRvC46AB4wydh/B8IIUMa7iF56Bm2yauQya1MFj5BF28LYLheuv+LHZt+Lofag0h8a65MpwzvWfvwUCaPTKoXuzn2HdjMku899fAzxzOWLJo3MEPuz0ltIBGJP+iG4ckBtkZE52rdATh9ogO
  template:
    metadata:
      name: r2-pg-backup
      namespace: test-phase3b
    type: Opaque
