---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: test-phase3b-pg-api-credentials
  namespace: test-phase3b
spec:
  encryptedData:
    password: AgCUfRnxMA0B6FXDu2qeNAwQMtYaIvkPxyH1UAbH2J9h7qbLCOXcR5nZEa4iYWrU3BOWRccgJ3W50B5oECbo1XDPqeIAXfk5ae5+GXN8fkUvOrPYnSWo7whEtey4YpFShw3RHPb8oX7WeS1xxGRbxtq1jKlmSwATNUWVfd6u94k8N6RWp9D3Fp0x3p84XkOHtoplhOhw6yYqA6U8Hu/JlSZke75JyLUnpSgLzw3OXtnKi5Ml/RKZU22mc3v/YzcGD7H/zDhto7vfOnRKP68+p3/SV3VQzMntWUsVGOUX8qSx5xbGW2mzM/kyLqKzX0hgXZXbb0bJeaMBu/wz81IN4pAYji5BpOv1W2V26Y/xLUqPWKAZIdEelsiV2kLdZj7KlH3ZujIQKgGsj++NhTnBUutePUi2OLD0Bq2XGYTvde4xEjcR/TcSEwB+E9zHUbOl44NWv8/xGyo7uEDLjN5uTu+tbUdSpwvdFFKOmHZyFTyP0lvVLsJr+93ypqOsfnVLW2OHK5opgzt1AVzebW/ulXgbeEuLdxZxALiWSzSjLrZ9N+6a/25gDcggPLxsxs5uM4pgX0GWKg/2LK+RTCDWpNGc3lXvIQnJ5mlvgr0AJ3f665ElMtYhGWPkxKle5b5LY+0r7I6ErB9ucq/r59AJEIeigCYlZ+L+2pOOIHATITE5yNo1Vbh9Z6NR0T0WO1uh8wAXhDiHvOSQ1/DD0v8NKAzSkQJHtaw67XzRhooiNr/rhQ==
    username: AgBYt1CkHoS9MtGITGNIEuWiXpXqkomRo+CRDVq/VgM0TOCm7nJUBoeZkTIAWTZmEbHpzmX3v2exWwhAeFECaxG1XLQfI8nOvWEqBVYnr4TdRo+npHxn1bul/whHfznDw2uhSYUh1yeOFCSAndxuFq6+onsNtiW47f0RKPK0Inn/nHBGlluRrUsA1fCzTenPI3k14yeJ8JiF/SY3Mel8EktOVZn6sLTojbP8gxD4KZmSJsK7z4rKBY3qAYetSZZfBt9vQ+Gi8/aueN3zJy8TUJW8LL7oczqB9z7KnyReEKSeC3gfJ/8pzKVDkB9aXctdqR0JTjY/ZGLa9Dvh5XXEdeYBAEpnrLRekx7MT1GFGvawHS2VWjBBhOpHbF8OJSIlC0htiMri16l3uQL/i2JTIBiLc+x2Ns8gTgMGTx2pBDFPjfIxVk2HcPFhC1o+EEcRY6cqaYtw2c90oj669RC/sqgt8ICN+6Q2PsujOoatvudZTyJz+R7RxCM/RV69sjthwoe8XwmveJqnRq78trby08SnNEYWjK5Ri0+Rdm4PrTZ4HQWx8JOqgbfVg5j5l0H+lwYvicogUTBvypjJYPJZe9+LkqIRzyKwucYoPOMjVPsEg58kyeqfOW9yOc9oNBdPh74vhRhyft98dMrTsB6vgomWm4PZRHjCFK0Lly4+yWNQyLJ8bIHjCi3u0sZbZ4KrYSnGP0E=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: test-phase3b-pg-api-credentials
      namespace: test-phase3b
    type: kubernetes.io/basic-auth
