name: Test Bool Only
on:
  workflow_call:
    inputs:
      app-name: { required: true, type: string }
      database-enabled:
        required: false
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.app-name }} db=${{ inputs.database-enabled }}"
