name: Test Perms No Secrets
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      database-enabled:
        required: false
        type: boolean
        default: false
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.app-name }}"
