name: Test No Any Perms
on:
  workflow_call:
    inputs:
      app-name: { required: true, type: string }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.app-name }}"
