name: Test Call With Setup
on:
  workflow_dispatch:
jobs:
  call:
    uses: ./.github/workflows/_test-with-setup-app.yml
    with:
      app-name: dummy
    secrets:
      APP_ID: ${{ secrets.HOMELAB_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.HOMELAB_APP_PRIVATE_KEY }}
      TF_CLOUDFLARE_TOKEN: ${{ secrets.TF_CLOUDFLARE_TOKEN }}
      TF_ZONE_ID: ${{ secrets.TF_ZONE_ID }}
      TF_TUNNEL_ID: ${{ secrets.TF_TUNNEL_ID }}
      TF_ACCOUNT_ID: ${{ secrets.TF_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
