apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps-default-deny.yaml
  - apps-allow-traefik.yaml
  - apps-allow-dns.yaml
  - apps-allow-kube-api.yaml
  - apps-allow-homepage-widgets.yaml
  - apps-allow-tailscale-proxy.yaml
  - traefik-default-deny.yaml
  - networking-default-deny.yaml
  - monitoring-default-deny.yaml
  - monitoring-allow-traefik.yaml
  - monitoring-allow-internal.yaml
